version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: loid-glosarium:v2.0
    networks:
      - db 
  db:
    image: mariadb:10.5
    volumes:
      - glosarium:/var/lib/mysql
    networks:
      - db
volumes:
  glosarium:
networks:
  db:
